### ISSUE TITLE
download

### ISSUE THREAD

**Issue by DaanvanderVeen** [B3Partners/flamingo-mob#35]
als een gemeente iets upload moet dat zichtbaar zijn als de provincie inlogt.

**Comment by mtoonen** [comment]
Zou moeten gebeuren. Wat zien jullie?

**Comment by DaanvanderVeen** [comment]
komt waarschijnlijk omdat in Firefox de knop niet goed is. Als ik er overheen hoover zie ik wel de naam van het bestand wat ik upload. In IE lukt het niet, kan ik ook niet opslaan.
