### ISSUE TITLE
MOB weergeven oppervlakte bij tekenen correctievoorstel

### ISSUE THREAD

**Issue by DaanvanderVeen** [B3Partners/flamingo-mob#81]
bij het tekenen van een correctievoorstel wordt nu de lengte van de getekende lijn weergegeven. 
Dit zou de oppervlakte moeten zijn.

**Comment by mtoonen** [comment]
Dit is een lastigere bug dan gedacht. Ik heb de standaard meting uitgezet bij het tekenen. De meetcomponent kan hierbij geconfigureerd worden als oplossing.
